### ISSUE TITLE
Add response objects

### ISSUE THREAD

**Issue by xsist10** [xsist10/HaveIBeenPwned#4]
At the moment the client returns responses as arrays. Swap this to return Value Objects (and see if you can make it backwards compatible by extending ArrayObject).

**Comment by peter279k** [comment]
@xsist10, I want to try to fix this issue?
Can you tell more details about the implementation?

Thanks.

**Comment by peter279k** [comment]
Hi @xsist10, thank you for your reply.
I think it makes sense and lets the different ```Response``` objects for the different response.
I will follow that approach that you suggest to implement and I also send the related PR.

If Having any problems after sending the PR, please feel free to add the comment and set the request changes :-).

Thanks.

**Comment by xsist10** [comment]
Sounds good. I look forward to seeing what you build. Shout if you want to
discuss anything :)
